### ISSUE TITLE
When a broken build is under investigation, present it with a different color, and make it display below the red ones

### ISSUE THREAD

**Issue by fernando-bernardino** [travcorp/tc-radiate#5]
It should be more easily to distinguish broken build that are under investigation from the one that are not. Maybe present broken builds under investigation as amber or brown.

**Comment by joshski** [comment]
Under investigation doesn't mean it's failing any less.

For this reason, I'd personally prefer it not to change colour, although it should still be easy to see who is investigating.

**Comment by slawomir-brzezinski-at-travcorp** [comment]
It's not failing any less, but a non-investigated issue is more important to tell people about. It's most often the only information that people can do anything about.
For this reason I think there's value in getting attention on them separately.

If we accept that ,then a color is just one way of distinguishing them from a lot of others which are being looked at already (one that's quite easy to implement).

It will still not be Green (can be less red only very slightly), and it will still be called a Failure.
