### ISSUE TITLE
Don't highlight one particular build

### ISSUE THREAD

**Issue by joshski** [travcorp/tc-radiate#6]
I assume the build that's highlighted on the right hand side of the screen is:

* the one that failed least recently
* or if none are failing currently, then the last build to pass

When we have lots of builds/teams sharing the same radiator, this layout doesn't make much sense to me. It suggests that the one at the top is somehow more important than the others. Although you could argue that it _is_ more important because it has failed for longer, the side-effect of highlighting a particular build seems to be that the ones below it are ignored until the "main failure" is fixed, when in fact they are failing for independent reasons.

Perhaps more importantly, it's hard to read the left side of the screen from a distance. Although @adiel has improved this with stylesheet tweaks, I personally think we should ditch the right side of the screen altogether, filling up the whole screen with what's on the left side (much like the Jenkins build monitor!). I would possibly even randomise the order of failing builds.

**Comment by slawomir-brzezinski-at-travcorp** [comment]
Thanks @joshski .
I'd like to revisit this problem after implementing https://github.com/travcorp/tc-radiate/issues/5 .
I feel that we presently have too many things that are red, and there's a lot of fight for the real-estate. @adiel 's changes are good for the most recent failing builds, but now they pushed a lot other builds out of the monitor (monitor near me only shows 3 builds). I agree that reclaiming space from the right hand side would improve some aspect of the situation, but it still might not guarantee that the important things are readable - allowing twice as many builds is still a guess about the real estate, and we may end up having to reduce the fonts again.
What I'd call 'enhancing prominence by importance' is just another stab at the problem of lack of real estate. It can helping people to judge the situation - makes it easy to act to things quickly.and I think the big image is an attempt at that. I think that the biggest problem is when noone is looking at an issue, so it does deserve the biggest prominence. And I'd expect that this should really usually be a situation which lasts for a very brief moment, so a single place for it is enough IMHO.
So, like I said, I'd implement #5 first and see whether removing the big image is really what we want.

**Comment by joshski** [comment]
Fine, whatevs. Actually it looks like we show the most recent failed build on the right hand side!

**Comment by slawomir-brzezinski-at-travcorp** [comment]
Closing, since as per above this was raised with assumption that the oldest failure is the highlighted.
Highlighting the latest does make sense as it's a good way to ensure that the information that is new to users is readable.
